In [54]:
import pandas as pd

In [55]:
movies = pd.read_csv('IMDb_Clean.csv')


In [56]:
movies.head()

Movie_name                                  Genre  \
0                       The Northman   Action, Adventure, Drama               
1                         The Batman       Action, Crime, Drama               
2                      The Lost City  Action, Adventure, Comedy               
3  Everything Everywhere All at Once  Action, Adventure, Comedy               
4                Operation Mincemeat                 Drama, War               

                                            Overview    Year   Time  Rating  \
0  From visionary director Robert Eggers comes Th...  2022.0  137.0     7.5   
1  When a sadistic serial killer begins murdering...  2022.0  176.0     8.0   
2  A reclusive romance novelist on a book tour wi...  2022.0  112.0     6.3   
3  An aging Chinese immigrant is swept up in an i...  2022.0  139.0     8.7   
4  During WWII, two intelligence officers use a c...  2021.0  128.0     6.7   

  Certificate     Votes  Gross(Million_$)  Metascore       Director  \
0         14A   75608.0               NaN       82.0  Robert Eggers   
1          PG  470895.0               NaN       72.0    Matt Reeves   
2          PG   38561.0               NaN       60.0      Aaron Nee   
3         14A   45050.0               NaN       81.0       Dan Kwan   
4         14A    6776.0               NaN       65.0    John Madden   

                                              Actors  
0  Alexander Skarsgård,Nicole Kidman,Claes Bang,E...  
1  Robert Pattinson,Zoë Kravitz,Jeffrey Wright,Co...  
2  Adam Nee,Sandra Bullock,Channing Tatum,Daniel ...  
3  Daniel Scheinert,Michelle Yeoh,Stephanie Hsu,K...  
4  Colin Firth,Matthew Macfadyen,Kelly Macdonald,...

In [57]:
movies["Genre"]

0          Action, Adventure, Drama            
1              Action, Crime, Drama            
2         Action, Adventure, Comedy            
3         Action, Adventure, Comedy            
4                        Drama, War            
                          ...                  
149917                                      NaN
149918                                      NaN
149919                        Drama            
149920                                      NaN
149921         Drama, Family, Music            
Name: Genre, Length: 149922, dtype: object

In [58]:
movies = movies.sort_values(["Votes"], ascending=False).head(10000)

In [59]:
movies = movies[["Movie_name", "Genre", "Overview", "Director", "Actors"]]

In [60]:
movies["Overview"] = movies["Overview"].str.replace('[^\dA-Za-z0-9 ]', '')

<ipython-input-60-b326c6653c29>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  movies["Overview"] = movies["Overview"].str.replace('[^\dA-Za-z0-9 ]', '')


In [61]:
movies.head()
movies.isna().sum()

Movie_name    0
Genre         0
Overview      1
Director      0
Actors        4
dtype: int64

In [62]:
movies["Genre"] = movies["Genre"].str.replace(","," ")

In [63]:
movies.head()
movies.isna().sum()

Movie_name    0
Genre         0
Overview      1
Director      0
Actors        4
dtype: int64

In [64]:
movies["Director"] = movies["Director"].str.replace(" ","")

In [65]:
movies

Movie_name  \
47                                  The Dark Knight   
102                                       Inception   
83                                     Interstellar   
172                           The Dark Knight Rises   
143                                Django Unchained   
...                                             ...   
6748                                   Sunlight Jr.   
13943                                        Oiktos   
53773  Celal Tan ve Ailesinin Asiri Acikli Hikayesi   
15223           Another Gay Sequel: Gays Gone Wild!   
33384                                Pilla Zamindar   

                                       Genre  \
47          Action  Crime  Drama               
102    Action  Adventure  Sci-Fi               
83      Adventure  Drama  Sci-Fi               
172         Action  Crime  Drama               
143               Drama  Western               
...                                      ...   
6748                       Drama               
13943                      Drama               
53773       Comedy  Crime  Drama               
15223            Comedy  Romance               
33384              Comedy  Drama               

                                                Overview          Director  \
47     When the menace known as the Joker wreaks havo...  ChristopherNolan   
102    A thief who steals corporate secrets through t...  ChristopherNolan   
83     A team of explorers travel through a wormhole ...  ChristopherNolan   
172    Eight years after the Jokers reign of anarchy ...  ChristopherNolan   
143    With the help of a German bountyhunter a freed...  QuentinTarantino   
...                                                  ...               ...   
6748   A Florida couple deals with an unexpected preg...     LaurieCollyer   
13943  The story of a man who feels happy only when h...     BabisMakridis   
53773  Celal Tan is a wellrespected constitutional la...          OnurÜnlü   
15223  Andy Nico Jarod and Griff reunite in Fort Laud...      ToddStephens   
33384  PJ has to go through a rough journey of living...           AshokG.   

                                                  Actors  
47     Christian Bale,Heath Ledger,Aaron Eckhart,Mich...  
102    Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot ...  
83     Matthew McConaughey,Anne Hathaway,Jessica Chas...  
172    Christian Bale,Tom Hardy,Anne Hathaway,Gary Ol...  
143    Jamie Foxx,Christoph Waltz,Leonardo DiCaprio,K...  
...                                                  ...  
6748   Naomi Watts,Matt Dillon,Tess Harper,Norman Reedus  
13943  Yannis Drakopoulos,Evi Saoulidou,Makis Papadim...  
53773  Onur Ünlü,Selçuk Yöntem,Ezgi Mola,Bülent Emin ...  
15223  Jonah Blechman,Jake Mosser,Aaron Michael Davie...  
33384           Nani,Haripriya,Bindhu Madhavi,Rao Ramesh  

[10000 rows x 5 columns]

In [66]:
movies['Actors'] = movies['Actors'].str.replace(" ", "")
movies['Actors'] = movies['Actors'].str.replace(",", " ")
movies

Movie_name  \
47                                  The Dark Knight   
102                                       Inception   
83                                     Interstellar   
172                           The Dark Knight Rises   
143                                Django Unchained   
...                                             ...   
6748                                   Sunlight Jr.   
13943                                        Oiktos   
53773  Celal Tan ve Ailesinin Asiri Acikli Hikayesi   
15223           Another Gay Sequel: Gays Gone Wild!   
33384                                Pilla Zamindar   

                                       Genre  \
47          Action  Crime  Drama               
102    Action  Adventure  Sci-Fi               
83      Adventure  Drama  Sci-Fi               
172         Action  Crime  Drama               
143               Drama  Western               
...                                      ...   
6748                       Drama               
13943                      Drama               
53773       Comedy  Crime  Drama               
15223            Comedy  Romance               
33384              Comedy  Drama               

                                                Overview          Director  \
47     When the menace known as the Joker wreaks havo...  ChristopherNolan   
102    A thief who steals corporate secrets through t...  ChristopherNolan   
83     A team of explorers travel through a wormhole ...  ChristopherNolan   
172    Eight years after the Jokers reign of anarchy ...  ChristopherNolan   
143    With the help of a German bountyhunter a freed...  QuentinTarantino   
...                                                  ...               ...   
6748   A Florida couple deals with an unexpected preg...     LaurieCollyer   
13943  The story of a man who feels happy only when h...     BabisMakridis   
53773  Celal Tan is a wellrespected constitutional la...          OnurÜnlü   
15223  Andy Nico Jarod and Griff reunite in Fort Laud...      ToddStephens   
33384  PJ has to go through a rough journey of living...           AshokG.   

                                                  Actors  
47     ChristianBale HeathLedger AaronEckhart Michael...  
102    LeonardoDiCaprio JosephGordon-Levitt ElliotPag...  
83     MatthewMcConaughey AnneHathaway JessicaChastai...  
172       ChristianBale TomHardy AnneHathaway GaryOldman  
143    JamieFoxx ChristophWaltz LeonardoDiCaprio Kerr...  
...                                                  ...  
6748       NaomiWatts MattDillon TessHarper NormanReedus  
13943  YannisDrakopoulos EviSaoulidou MakisPapadimitr...  
53773  OnurÜnlü SelçukYöntem EzgiMola BülentEminYarar...  
15223  JonahBlechman JakeMosser AaronMichaelDavies Ji...  
33384             Nani Haripriya BindhuMadhavi RaoRamesh  

[10000 rows x 5 columns]

In [67]:
movies["tag"] = movies["Overview"].map(str) + " " + movies["Actors"].map(str)

In [68]:
movies.reset_index(inplace=True)

In [69]:
movies.head()
movies.isna().sum()

index         0
Movie_name    0
Genre         0
Overview      1
Director      0
Actors        4
tag           0
dtype: int64

In [70]:
movies.isna().sum()

index         0
Movie_name    0
Genre         0
Overview      1
Director      0
Actors        4
tag           0
dtype: int64

In [71]:
movies["tag"]

0       When the menace known as the Joker wreaks havo...
1       A thief who steals corporate secrets through t...
2       A team of explorers travel through a wormhole ...
3       Eight years after the Jokers reign of anarchy ...
4       With the help of a German bountyhunter a freed...
                              ...                        
9995    A Florida couple deals with an unexpected preg...
9996    The story of a man who feels happy only when h...
9997    Celal Tan is a wellrespected constitutional la...
9998    Andy Nico Jarod and Griff reunite in Fort Laud...
9999    PJ has to go through a rough journey of living...
Name: tag, Length: 10000, dtype: object

In [72]:

new = movies.drop(columns=['Overview','Actors','index'])
new

Movie_name  \
0                                  The Dark Knight   
1                                        Inception   
2                                     Interstellar   
3                            The Dark Knight Rises   
4                                 Django Unchained   
...                                            ...   
9995                                  Sunlight Jr.   
9996                                        Oiktos   
9997  Celal Tan ve Ailesinin Asiri Acikli Hikayesi   
9998           Another Gay Sequel: Gays Gone Wild!   
9999                                Pilla Zamindar   

                                      Genre          Director  \
0          Action  Crime  Drama              ChristopherNolan   
1     Action  Adventure  Sci-Fi              ChristopherNolan   
2      Adventure  Drama  Sci-Fi              ChristopherNolan   
3          Action  Crime  Drama              ChristopherNolan   
4                Drama  Western              QuentinTarantino   
...                                     ...               ...   
9995                      Drama                 LaurieCollyer   
9996                      Drama                 BabisMakridis   
9997       Comedy  Crime  Drama                      OnurÜnlü   
9998            Comedy  Romance                  ToddStephens   
9999              Comedy  Drama                       AshokG.   

                                                    tag  
0     When the menace known as the Joker wreaks havo...  
1     A thief who steals corporate secrets through t...  
2     A team of explorers travel through a wormhole ...  
3     Eight years after the Jokers reign of anarchy ...  
4     With the help of a German bountyhunter a freed...  
...                                                 ...  
9995  A Florida couple deals with an unexpected preg...  
9996  The story of a man who feels happy only when h...  
9997  Celal Tan is a wellrespected constitutional la...  
9998  Andy Nico Jarod and Griff reunite in Fort Laud...  
9999  PJ has to go through a rough journey of living...  

[10000 rows x 4 columns]

In [153]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features=1000,stop_words='english')

tfidf = vectorizer.fit_transform(new['tag'])


In [154]:
words =  pd.DataFrame(vectorizer.vocabulary_.items()).sort_values(1)
words

0    1
902         10    0
342      1960s    1
618      1970s    2
667      1980s    3
205  abandoned    4
..         ...  ...
99       young  995
147    younger  996
538      youth  997
373     zombie  998
937    zombies  999

[1000 rows x 2 columns]

In [158]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1000,stop_words='english')

In [159]:
new['tag'].isna().sum()

0

In [160]:
vector = cv.fit_transform(new['tag']).toarray()

In [161]:
vector.shape


(10000, 1000)

In [162]:
type(vector)

numpy.ndarray

In [163]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [164]:
pd.set_option('display.max_columns', None)

In [165]:
pd.DataFrame(vector,columns=words[0])

0     10  1960s  1970s  1980s  abandoned  abducted  accident  accidentally  \
0      0      0      0      0          0         0         0             0   
1      0      0      0      0          0         0         0             0   
2      0      0      0      0          0         0         0             0   
3      0      0      0      0          0         0         0             0   
4      0      0      0      0          0         0         0             0   
...   ..    ...    ...    ...        ...       ...       ...           ...   
9995   0      0      0      0          0         0         0             0   
9996   0      0      0      0          0         0         0             0   
9997   0      0      0      0          0         0         0             0   
9998   0      0      0      0          0         0         0             0   
9999   0      0      0      0          0         0         0             0   

0     act  action  actor  actress  adult  adventure  adventures  affair  age  \
0       0       0      0        0      0          0           0       0    0   
1       0       0      0        0      0          0           0       0    0   
2       0       0      0        0      0          0           0       0    0   
3       0       0      0        0      0          0           0       0    0   
4       0       0      0        0      0          0           0       0    0   
...   ...     ...    ...      ...    ...        ...         ...     ...  ...   
9995    0       0      0        0      0          0           0       0    0   
9996    0       0      0        0      0          0           0       0    0   
9997    0       0      0        0      0          0           0       0    0   
9998    0       0      0        0      0          0           0       0    0   
9999    0       0      0        0      0          0           0       0    0   

0     agent  agents  aging  ago  agrees  air  ajaydevgn  akshaykumar  alien  \
0         0       0      0    0       0    0          0            0      0   
1         0       0      0    0       0    0          0            0      0   
2         0       0      0    0       0    0          0            0      0   
3         0       0      0    0       0    0          0            0      0   
4         0       0      0    0       0    0          0            0      0   
...     ...     ...    ...  ...     ...  ...        ...          ...    ...   
9995      0       0      0    0       0    0          0            0      0   
9996      0       0      0    0       0    0          0            0      0   
9997      0       0      0    0       0    0          0            0      0   
9998      0       0      0    0       0    0          0            0      0   
9999      0       0      0    0       0    0          0            0      0   

0     alive  ambitious  america  american  amitabhbachchan  ancient  angeles  \
0         0          0        0         0                0        0        0   
1         0          0        0         0                0        0        0   
2         0          0        0         0                0        0        0   
3         0          0        0         0                0        0        0   
4         0          0        0         0                0        0        0   
...     ...        ...      ...       ...              ...      ...      ...   
9995      0          0        0         0                0        0        0   
9996      0          0        0         0                0        0        0   
9997      0          0        0         0                0        0        0   
9998      0          0        0         0                0        0        0   
9999      0          0        0         0                0        0        0   

0     annakendrick  annehathaway  apart  apartment  apocalypse  appears  army  \
0                0             0      0          0           0        0     0   
1                0            

In [166]:
movies[['Director','Genre']]

Director                                  Genre
0     ChristopherNolan       Action  Crime  Drama            
1     ChristopherNolan  Action  Adventure  Sci-Fi            
2     ChristopherNolan   Adventure  Drama  Sci-Fi            
3     ChristopherNolan       Action  Crime  Drama            
4     QuentinTarantino             Drama  Western            
...                ...                                    ...
9995     LaurieCollyer                      Drama            
9996     BabisMakridis                      Drama            
9997          OnurÜnlü       Comedy  Crime  Drama            
9998      ToddStephens            Comedy  Romance            
9999           AshokG.              Comedy  Drama            

[10000 rows x 2 columns]

In [196]:
movies['Genre'] = movies['Genre'].apply(lambda x : x.strip())

In [167]:
from sklearn.preprocessing import OneHotEncoder

In [207]:
onehot_encoder = OneHotEncoder(sparse=False)
onehot = onehot_encoder.fit_transform(movies[['Director','Genre']])
print(onehot)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [208]:
onehot_encoder.categories_

[array(['300', '7-beon-bang-uiseon-mul', 'A.L.Vijay', ..., 'ÖzhanEren',
        'ÜmitÜnal', 'Üvegtigris'], dtype=object),
 array(['Action', 'Action  Adventure', 'Action  Adventure  Biography',
        'Action  Adventure  Comedy', 'Action  Adventure  Crime',
        'Action  Adventure  Drama', 'Action  Adventure  Family',
        'Action  Adventure  Fantasy', 'Action  Adventure  History',
        'Action  Adventure  Horror', 'Action  Adventure  Mystery',
        'Action  Adventure  Romance', 'Action  Adventure  Sci-Fi',
        'Action  Adventure  Thriller', 'Action  Adventure  Western',
        'Action  Biography  Comedy', 'Action  Biography  Crime',
        'Action  Biography  Drama', 'Action  Biography  Thriller',
        'Action  Comedy', 'Action  Comedy  Crime', 'Action  Comedy  Drama',
        'Action  Comedy  Family', 'Action  Comedy  Fantasy',
        'Action  Comedy  History', 'Action  Comedy  Horror',
        'Action  Comedy  Music', 'Action  Comedy  Musical',
        'Action 

In [209]:
onehot.shape

(10000, 5965)

In [210]:
vector.shape

(10000, 1000)

In [183]:
import numpy as np
merged_vectore = np.hstack((vector,onehot))

In [184]:
merged_vectore.shape

(10000, 6965)

In [185]:
from sklearn.metrics.pairwise import cosine_similarity

In [187]:
similarity = cosine_similarity(merged_vectore)

In [89]:
similarity

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.11952286, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.11952286, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [188]:
new[new['Movie_name'] == 'The Dark Knight'].index[0]

0

In [189]:
def recommend(movie):
    index = new[new['Movie_name'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new.iloc[i[0]].Movie_name)

In [192]:
recommend('Avatar')

Power Rangers
Fantastic Beasts: The Secrets of Dumbledore
Mune, le gardien de la lune
Noah
Suicide Squad


In [34]:
import pickle

In [35]:
pickle.dump(new,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))